# Generated by Django 5.2.17 on 2026-09-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('in_progress', 'В обробці'), ('agreed', 'Узгоджено'), ('done', 'Виконано'), ('cancelled', 'Скасовано')], default='new', max_length=20, verbose_name='Статус')),
                ('name', models.CharField(max_length=128, verbose_name='Ім’я')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('consent', models.BooleanField(verbose_name='Згода на ПД')),
                ('language', models.CharField(default='uk', max_length=2, verbose_name='Мова')),
            ],
            options={
                'verbose_name': 'Звернення',
                'verbose_name_plural': 'Звернення «Контакти»',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('in_progress', 'В обробці'), ('agreed', 'Узгоджено'), ('done', 'Виконано'), ('cancelled', 'Скасовано')], default='new', max_length=20, verbose_name='Статус')),
                ('product_name', models.CharField(max_length=255, verbose_name='Модель')),
                ('product_slug', models.SlugField(blank=True, max_length=128, verbose_name='Slug моделі')),
                ('fabric_name', models.CharField(blank=True, max_length=128, verbose_name='Тканина')),
                ('shade_name', models.CharField(blank=True, max_length=128, verbose_name='Відтінок')),
                ('sku', models.CharField(blank=True, max_length=64, verbose_name='Артикул')),
                ('price', models.PositiveIntegerField(verbose_name='Ціна на момент заявки')),
                ('name', models.CharField(max_length=128, verbose_name='ПІБ')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('fulfillment', models.CharField(choices=[('pickup', 'Самовивіз / завантаження'), ('own_car', 'Власним авто')], default='pickup', max_length=20, verbose_name='Отримання')),
                ('consent', models.BooleanField(verbose_name='Згода на ПД')),
                ('language', models.CharField(default='uk', max_length=2, verbose_name='Мова')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення товарів',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnershipLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('in_progress', 'В обробці'), ('agreed', 'Узгоджено'), ('done', 'Виконано'), ('cancelled', 'Скасовано')], default='new', max_length=20, verbose_name='Статус')),
                ('company', models.CharField(max_length=255, verbose_name='Компанія / ПІБ')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Контактна особа')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='Місто')),
                ('collab_type', models.CharField(blank=True, choices=[('dealer', 'Дилер'), ('salon', 'Салон'), ('designer', 'Дизайнер'), ('wholesale', 'Гурт')], max_length=20, verbose_name='Тип співпраці')),
                ('message', models.TextField(blank=True, verbose_name='Повідомлення')),
                ('consent', models.BooleanField(verbose_name='Згода на ПД')),
                ('language', models.CharField(default='uk', max_length=2, verbose_name='Мова')),
            ],
            options={
                'verbose_name': 'Заявка на співпрацю',
                'verbose_name_plural': 'Заявки «Співпраця»',
                'ordering': ['-created_at'],
            },
        ),
    ]
