# Generated by Django 5.2.17 on 2026-10-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnershiplead',
            name='city',
            field=models.CharField(max_length=128, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='partnershiplead',
            name='company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Компанія / ПІБ'),
        ),
        migrations.AlterField(
            model_name='partnershiplead',
            name='consent',
            field=models.BooleanField(default=True, verbose_name='Згода на ПД'),
        ),
        migrations.AlterField(
            model_name='partnershiplead',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Контактна особа'),
        ),
    ]
