# Generated by Django 5.2.17 on 2026-10-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_collab_dealer_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlead',
            name='consent',
            field=models.BooleanField(verbose_name='Згода на обробку персональних даних'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='consent',
            field=models.BooleanField(verbose_name='Згода на обробку персональних даних'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='product_slug',
            field=models.SlugField(blank=True, max_length=128, verbose_name='URL моделі'),
        ),
        migrations.AlterField(
            model_name='partnershiplead',
            name='consent',
            field=models.BooleanField(default=True, verbose_name='Згода на обробку персональних даних'),
        ),
    ]
