services:
  nginx:
    restart: always
  certbot:
    restart: always
  backend:
    restart: always
    env_file:
      - .env
    environment:
      PYTHONPATH: /app/src
  db:
    restart: always
    env_file:
      - .env
