# Generated by Django 5.2.17 on 2026-09-21 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('name_uk', models.CharField(max_length=128, verbose_name='Назва (UK)')),
                ('name_ru', models.CharField(blank=True, max_length=128, verbose_name='Назва (RU)')),
                ('surcharge', models.PositiveIntegerField(default=0, verbose_name='Націнка, грн')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Видима')),
            ],
            options={
                'verbose_name': 'Тканина',
                'verbose_name_plural': 'Тканини',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('seo_title_uk', models.CharField(blank=True, max_length=512, verbose_name='SEO title (UK)')),
                ('seo_title_ru', models.CharField(blank=True, max_length=512, verbose_name='SEO title (RU)')),
                ('seo_description_uk', models.TextField(blank=True, verbose_name='SEO description (UK)')),
                ('seo_description_ru', models.TextField(blank=True, verbose_name='SEO description (RU)')),
                ('slug', models.SlugField(max_length=64, verbose_name='Slug')),
                ('name_uk', models.CharField(max_length=128, verbose_name='Назва (UK)')),
                ('name_ru', models.CharField(blank=True, max_length=128, verbose_name='Назва (RU)')),
                ('intro_uk', models.TextField(blank=True, verbose_name='Вступ (UK)')),
                ('intro_ru', models.TextField(blank=True, verbose_name='Вступ (RU)')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Фото плитки')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Видима')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='Батьківська')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['sort', 'id'],
                'unique_together': {('parent', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('seo_title_uk', models.CharField(blank=True, max_length=512, verbose_name='SEO title (UK)')),
                ('seo_title_ru', models.CharField(blank=True, max_length=512, verbose_name='SEO title (RU)')),
                ('seo_description_uk', models.TextField(blank=True, verbose_name='SEO description (UK)')),
                ('seo_description_ru', models.TextField(blank=True, verbose_name='SEO description (RU)')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('sku', models.CharField(blank=True, max_length=64, verbose_name='Артикул')),
                ('name_uk', models.CharField(max_length=128, verbose_name='Назва (UK)')),
                ('name_ru', models.CharField(blank=True, max_length=128, verbose_name='Назва (RU)')),
                ('type_uk', models.CharField(blank=True, max_length=128, verbose_name='Тип (UK)')),
                ('type_ru', models.CharField(blank=True, max_length=128, verbose_name='Тип (RU)')),
                ('base_price', models.PositiveIntegerField(verbose_name='Базова ціна, грн')),
                ('badge', models.CharField(blank=True, choices=[('NEW', 'NEW'), ('TOP', 'TOP'), ('HIT', 'Хіт')], max_length=8, verbose_name='Бейдж')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наявності')),
                ('is_active', models.BooleanField(default=True, verbose_name='Видимий')),
                ('description_uk', models.TextField(blank=True, verbose_name='Опис (UK)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Опис (RU)')),
                ('care_uk', models.TextField(blank=True, verbose_name='Догляд (UK)')),
                ('care_ru', models.TextField(blank=True, verbose_name='Догляд (RU)')),
                ('dims_uk', models.CharField(blank=True, max_length=255, verbose_name='Розміри (UK)')),
                ('dims_ru', models.CharField(blank=True, max_length=255, verbose_name='Розміри (RU)')),
                ('default_image', models.ImageField(blank=True, upload_to='products/', verbose_name='Основне фото')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductFabricPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('price', models.PositiveIntegerField(verbose_name='Ціна, грн')),
                ('sku', models.CharField(blank=True, max_length=64, verbose_name='Артикул варіанта')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='catalog.fabric', verbose_name='Тканина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_prices', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Ціна тканини',
                'verbose_name_plural': 'Ціни тканин',
            },
        ),
        migrations.CreateModel(
            name='Shade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('slug', models.SlugField(max_length=64, verbose_name='Slug')),
                ('name_uk', models.CharField(max_length=128, verbose_name='Назва (UK)')),
                ('name_ru', models.CharField(blank=True, max_length=128, verbose_name='Назва (RU)')),
                ('hex_color', models.CharField(max_length=7, verbose_name='HEX')),
                ('swatch', models.ImageField(blank=True, upload_to='shades/', verbose_name='Міні-фото кружечка')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Видимий')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shades', to='catalog.fabric', verbose_name='Тканина')),
            ],
            options={
                'verbose_name': 'Відтінок',
                'verbose_name_plural': 'Відтінки',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductShadeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('image', models.ImageField(blank=True, upload_to='products/shades/', verbose_name='Фото')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shade_images', to='catalog.product', verbose_name='Товар')),
                ('shade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='catalog.shade', verbose_name='Відтінок')),
            ],
            options={
                'verbose_name': 'Фото відтінку',
                'verbose_name_plural': 'Фото відтінків',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_available'], name='catalog_pro_is_acti_f6baa6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name_uk'], name='catalog_pro_name_uk_24b861_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='catalog_pro_sku_2c4c34_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productfabricprice',
            unique_together={('product', 'fabric')},
        ),
        migrations.AlterUniqueTogether(
            name='shade',
            unique_together={('fabric', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='productshadeimage',
            unique_together={('product', 'shade', 'sort')},
        ),
    ]
