# Generated by Django 5.2.17 on 2026-10-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='spec_filling_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Характеристика: наповнення (RU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_filling_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Характеристика: наповнення (UK)'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_frame_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Характеристика: каркас (RU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_frame_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Характеристика: каркас (UK)'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_mechanism_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Характеристика: механізм (RU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_mechanism_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Характеристика: механізм (UK)'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_storage_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Характеристика: ніші (RU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_storage_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Характеристика: ніші (UK)'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_textile_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Характеристика: тканина (RU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_textile_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Характеристика: тканина (UK)'),
        ),
    ]
