# Generated by Django 5.2.17 on 2026-10-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='productshadeimage',
            name='hex_override',
            field=models.CharField(blank=True, help_text='Якщо задано — замінює колір кружечка лише для цього товару', max_length=7, verbose_name='HEX кружечка (override)'),
        ),
    ]
