# Generated by Django 5.2.17 on 2026-10-01 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productshadeimage_hex_override'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productshadeimage',
            options={'ordering': ['sort', 'id'], 'verbose_name': 'Фото відтінку (застаріле)', 'verbose_name_plural': 'Фото відтінків (застаріле)'},
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('slug', models.SlugField(max_length=64, verbose_name='Slug')),
                ('name_uk', models.CharField(max_length=64, verbose_name='Назва (UK)')),
                ('name_ru', models.CharField(blank=True, max_length=64, verbose_name='Назва (RU)')),
                ('hex_color', models.CharField(max_length=7, verbose_name='HEX кружечка')),
                ('image', models.ImageField(blank=True, upload_to='products/colors/', verbose_name='Фото кольору')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Видимий')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Колір товару',
                'verbose_name_plural': 'Кольори товару',
                'ordering': ['sort', 'id'],
                'unique_together': {('product', 'slug')},
            },
        ),
    ]
