# Generated by Django 5.2.17 on 2026-10-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=64, verbose_name='URL-адреса'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL-адреса'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL-адреса'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='slug',
            field=models.SlugField(max_length=64, verbose_name='URL-адреса'),
        ),
        migrations.AlterField(
            model_name='shade',
            name='slug',
            field=models.SlugField(max_length=64, verbose_name='URL-адреса'),
        ),
    ]
