# Generated by Django 5.2.17 on 2026-10-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_admin_uk_slugs_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='intro_ru',
            field=models.TextField(blank=True, verbose_name='Вступ (ru)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='intro_uk',
            field=models.TextField(blank=True, verbose_name='Вступ (ukr)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Назва (ru)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_uk',
            field=models.CharField(max_length=128, verbose_name='Назва (ukr)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_description_ru',
            field=models.TextField(blank=True, verbose_name='SEO description (ru)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_description_uk',
            field=models.TextField(blank=True, verbose_name='SEO description (ukr)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_title_ru',
            field=models.CharField(blank=True, max_length=512, verbose_name='SEO title (ru)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_title_uk',
            field=models.CharField(blank=True, max_length=512, verbose_name='SEO title (ukr)'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='name_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Назва (ru)'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='name_uk',
            field=models.CharField(max_length=128, verbose_name='Назва (ukr)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='care_ru',
            field=models.TextField(blank=True, verbose_name='Догляд (ru)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='care_uk',
            field=models.TextField(blank=True, verbose_name='Догляд (ukr)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Опис (ru)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_uk',
            field=models.TextField(blank=True, verbose_name='Опис (ukr)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dims_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Розміри (ru)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dims_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Розміри (ukr)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Назва (ru)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_uk',
            field=models.CharField(max_length=128, verbose_name='Назва (ukr)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_description_ru',
            field=models.TextField(blank=True, verbose_name='SEO description (ru)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_description_uk',
            field=models.TextField(blank=True, verbose_name='SEO description (ukr)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_title_ru',
            field=models.CharField(blank=True, max_length=512, verbose_name='SEO title (ru)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_title_uk',
            field=models.CharField(blank=True, max_length=512, verbose_name='SEO title (ukr)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spec_filling_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Характеристика: наповнення (ru)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spec_filling_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Характеристика: наповнення (ukr)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spec_frame_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Характеристика: каркас (ru)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spec_frame_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Характеристика: каркас (ukr)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spec_mechanism_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Характеристика: механізм (ru)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spec_mechanism_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Характеристика: механізм (ukr)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spec_storage_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Характеристика: ніші (ru)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spec_storage_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Характеристика: ніші (ukr)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spec_textile_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Характеристика: тканина (ru)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spec_textile_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Характеристика: тканина (ukr)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Тип (ru)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_uk',
            field=models.CharField(blank=True, max_length=128, verbose_name='Тип (ukr)'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='name_ru',
            field=models.CharField(blank=True, max_length=64, verbose_name='Назва (ru)'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='name_uk',
            field=models.CharField(max_length=64, verbose_name='Назва (ukr)'),
        ),
        migrations.AlterField(
            model_name='shade',
            name='name_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Назва (ru)'),
        ),
        migrations.AlterField(
            model_name='shade',
            name='name_uk',
            field=models.CharField(max_length=128, verbose_name='Назва (ukr)'),
        ),
    ]
