# Generated by Django 5.2.17 on 2026-10-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_lang_labels_ukr_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='intro_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='intro_uk',
        ),
    ]
