# Generated by Django 5.2.17 on 2026-10-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_category_intro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='surcharge',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Націнка, грн'),
        ),
    ]
