# Generated by Django 5.2.17 on 2026-10-09 07:03

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_characteristic_product_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='default_image',
            field=core.fields.WebPImageField(blank=True, upload_to='products/', verbose_name='Основне фото'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='image',
            field=core.fields.WebPImageField(blank=True, upload_to='products/colors/', verbose_name='Фото товару цього кольору'),
        ),
        migrations.AlterField(
            model_name='shade',
            name='swatch',
            field=core.fields.WebPImageField(blank=True, upload_to='shades/', verbose_name='Міні-фото кружечка'),
        ),
    ]
