# Generated by Django 6.0.1 on 2026-09-22 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('image', models.ImageField(upload_to='home/slides/', verbose_name='Зображення')),
                ('title_uk', models.CharField(max_length=120, verbose_name='Заголовок (UK)')),
                ('title_ru', models.CharField(blank=True, max_length=120, verbose_name='Заголовок (RU)')),
                ('subtitle_uk', models.CharField(blank=True, max_length=255, verbose_name='Підпис (UK)')),
                ('subtitle_ru', models.CharField(blank=True, max_length=255, verbose_name='Підпис (RU)')),
                ('cta_uk', models.CharField(default='Дивитись каталог', max_length=64, verbose_name='Кнопка (UK)')),
                ('cta_ru', models.CharField(blank=True, max_length=64, verbose_name='Кнопка (RU)')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='core.homepage', verbose_name='Головна')),
            ],
            options={
                'verbose_name': 'Hero слайд',
                'verbose_name_plural': 'Hero слайди',
                'ordering': ('sort', 'id'),
            },
        ),
    ]
