# Generated by Django 6.0.1 on 2026-09-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hero_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_body_ru',
            field=models.TextField(blank=True, verbose_name='Про ROSSA — текст (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_body_uk',
            field=models.TextField(blank=True, verbose_name='Про ROSSA — текст (UK)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Про ROSSA — заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Про ROSSA — заголовок (UK)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_video',
            field=models.FileField(blank=True, upload_to='home/video/', verbose_name='Про ROSSA — відео'),
        ),
    ]
