# Generated by Django 5.2.17 on 2026-10-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_about_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='image_alt_ru',
            field=models.CharField(blank=True, max_length=160, verbose_name='Alt зображення (RU)'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image_alt_uk',
            field=models.CharField(blank=True, max_length=160, verbose_name='Alt зображення (UK)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_2',
            field=models.CharField(blank=True, max_length=64, verbose_name='Телефон 2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_3',
            field=models.CharField(blank=True, max_length=64, verbose_name='Телефон 3'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='TikTok URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(max_length=64, verbose_name='Телефон 1'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_url',
            field=models.URLField(blank=True, verbose_name='Telegram URL'),
        ),
    ]
