# Generated by Django 5.2.17 on 2026-10-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_client_edits_contacts_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabpage',
            name='advantages_title_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Заголовок переваг (RU)'),
        ),
        migrations.AddField(
            model_name='collabpage',
            name='advantages_title_uk',
            field=models.CharField(blank=True, default='Наші переваги', max_length=128, verbose_name='Заголовок переваг (UK)'),
        ),
        migrations.AlterField(
            model_name='collabpage',
            name='benefits',
            field=models.JSONField(blank=True, default=list, help_text='Список: icon (years|production|guarantee|collections|design), title_uk, title_ru', verbose_name='Переваги'),
        ),
        migrations.AlterField(
            model_name='collabpage',
            name='sub_uk',
            field=models.TextField(blank=True, verbose_name='Вступ (UK)'),
        ),
    ]
