# Generated by Django 5.2.17 on 2026-10-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_collab_advantages_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabpage',
            name='dealer_support',
            field=models.JSONField(blank=True, default=list, help_text='Список: title_uk, title_ru, body_uk, body_ru', verbose_name='Підтримка дилера'),
        ),
        migrations.AddField(
            model_name='collabpage',
            name='dealer_support_title_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Заголовок підтримки дилера (RU)'),
        ),
        migrations.AddField(
            model_name='collabpage',
            name='dealer_support_title_uk',
            field=models.CharField(blank=True, default='Підтримка нашого дилера:', max_length=128, verbose_name='Заголовок підтримки дилера (UK)'),
        ),
        migrations.AddField(
            model_name='collabpage',
            name='form_image',
            field=models.ImageField(blank=True, upload_to='collab/', verbose_name='Фото біля форми'),
        ),
    ]
