# Generated by Django 5.2.17 on 2026-10-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_collab_dealer_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='milestones_title_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Заголовок віх (RU)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='milestones_title_uk',
            field=models.CharField(blank=True, default='Ключові віхи нашої історії', max_length=128, verbose_name='Заголовок віх (UK)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Підзаголовок (RU)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='subtitle_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Підзаголовок (UK)'),
        ),
    ]
