# Generated by Django 5.2.17 on 2026-10-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_about_evolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='logo_images',
            field=models.JSONField(blank=True, default=list, help_text='Список: image, year, label_uk, label_ru.', verbose_name='Логотипи (галерея)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='logo_title_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Заголовок логотипів (RU)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='logo_title_uk',
            field=models.CharField(blank=True, default='Еволюція логотипу', max_length=128, verbose_name='Заголовок логотипів (UK)'),
        ),
    ]
