# Generated by Django 5.2.17 on 2026-10-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_about_logo_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChromeStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('header_bg', models.CharField(blank=True, max_length=32, verbose_name='Шапка — фон')),
                ('header_text', models.CharField(blank=True, max_length=32, verbose_name='Шапка — текст')),
                ('footer_top_bg', models.CharField(blank=True, max_length=32, verbose_name='Підвал (верх) — фон')),
                ('footer_top_text', models.CharField(blank=True, max_length=32, verbose_name='Підвал (верх) — текст')),
                ('footer_bottom_bg', models.CharField(blank=True, max_length=32, verbose_name='Підвал (низ) — фон')),
                ('footer_bottom_text', models.CharField(blank=True, max_length=32, verbose_name='Підвал (низ) — текст')),
            ],
            options={
                'verbose_name': 'Шапка і підвал',
                'verbose_name_plural': 'Шапка і підвал',
            },
        ),
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('seo_title_uk', models.CharField(blank=True, max_length=512, verbose_name='SEO title (UK)')),
                ('seo_title_ru', models.CharField(blank=True, max_length=512, verbose_name='SEO title (RU)')),
                ('seo_description_uk', models.TextField(blank=True, verbose_name='SEO description (UK)')),
                ('seo_description_ru', models.TextField(blank=True, verbose_name='SEO description (RU)')),
                ('title_uk', models.CharField(default='Контакти', max_length=255, verbose_name='Заголовок (UK)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (RU)')),
                ('intro_uk', models.TextField(blank=True, verbose_name='Вступ (UK)')),
                ('intro_ru', models.TextField(blank=True, verbose_name='Вступ (RU)')),
                ('form_title_uk', models.CharField(blank=True, default='Напишіть нам', max_length=128, verbose_name='Заголовок форми (UK)')),
                ('form_title_ru', models.CharField(blank=True, max_length=128, verbose_name='Заголовок форми (RU)')),
            ],
            options={
                'verbose_name': 'Контакти',
                'verbose_name_plural': 'Контакти',
            },
        ),
        migrations.CreateModel(
            name='PageStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('page', models.CharField(choices=[('home', 'Головна'), ('about', 'Про нас'), ('collab', 'Співпраця'), ('contacts', 'Контакти'), ('delivery', 'Доставка'), ('offer', 'Оферта'), ('privacy', 'Політика конфіденційності'), ('catalog', 'Каталог')], max_length=32, unique=True, verbose_name='Сторінка')),
                ('background_color', models.CharField(blank=True, help_text='Фон між шапкою і підвалом. Порожнє — як на сайті за замовчуванням.', max_length=32, verbose_name='Колір фону')),
                ('text_color', models.CharField(blank=True, help_text='Основний текст сторінки. Порожнє — як на сайті за замовчуванням.', max_length=32, verbose_name='Колір тексту')),
                ('accent_color', models.CharField(blank=True, help_text='Акцентні елементи. Порожнє — як на сайті за замовчуванням.', max_length=32, verbose_name='Колір підсвітки')),
            ],
            options={
                'verbose_name': 'Оформлення сторінки',
                'verbose_name_plural': 'Оформлення сторінок',
                'ordering': ['page'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPage',
            fields=[
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставка',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.legalpage',),
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Підвал сайту',
                'verbose_name_plural': 'Підвал сайту',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Шапка сайту',
                'verbose_name_plural': 'Шапка сайту',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='OfferPage',
            fields=[
            ],
            options={
                'verbose_name': 'Оферта',
                'verbose_name_plural': 'Оферта',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.legalpage',),
        ),
        migrations.CreateModel(
            name='PrivacyPage',
            fields=[
            ],
            options={
                'verbose_name': 'Політика конфіденційності',
                'verbose_name_plural': 'Політика конфіденційності',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.legalpage',),
        ),
    ]
