# Generated by Django 5.2.17 on 2026-10-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cms_admin_styles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='logo_title_ru',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='logo_title_uk',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='values',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='cta_ru',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='cta_uk',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='subtitle_ru',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='subtitle_uk',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='cta_catalog_ru',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='cta_catalog_uk',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_poster',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_sub_ru',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_sub_uk',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_title_ru',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_title_uk',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_video',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image_alt_ru',
            field=models.CharField(blank=True, max_length=160, verbose_name='Підпис / alt (RU)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image_alt_uk',
            field=models.CharField(blank=True, max_length=160, verbose_name='Підпис / alt (UK)'),
        ),
    ]
