# Generated by Django 5.2.17 on 2026-10-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_dead_cms_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='craft_body_ru',
            field=models.TextField(blank=True, verbose_name='Текст блоку «виробництво» (RU)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='craft_body_uk',
            field=models.TextField(verbose_name='Текст блоку «виробництво» (UK)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='craft_link_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Текст посилання «Про нас» (RU)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='craft_link_uk',
            field=models.CharField(blank=True, max_length=128, verbose_name='Текст посилання «Про нас» (UK)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='craft_title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок блоку «виробництво» (RU)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='craft_title_uk',
            field=models.CharField(max_length=255, verbose_name='Заголовок блоку «виробництво» (UK)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_banner_title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст банера-запрошення (RU)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_banner_title_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст банера-запрошення (UK)'),
        ),
    ]
