# Generated by Django 5.2.17 on 2026-10-02 10:28

import core.collab_form_copy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cms_plain_text_to_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabpage',
            name='form_fields',
            field=models.JSONField(blank=True, default=core.collab_form_copy.default_collab_form_copy, help_text='Підписи та підказки полів заявки (укр / рос).', verbose_name='Поля форми'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='evolution_images',
            field=models.JSONField(blank=True, default=list, help_text='Галерея фото. Порядок = порядок показу.', verbose_name='Еволюція диванів'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='logo_images',
            field=models.JSONField(blank=True, default=list, help_text='Рядки: фото, рік, підписи. Без JSON.', verbose_name='Логотипи (галерея)'),
        ),
        migrations.AlterField(
            model_name='collabpage',
            name='benefits',
            field=models.JSONField(blank=True, default=list, help_text='Додавайте рядки кнопкою нижче. Іконку обирайте зі списку.', verbose_name='Переваги'),
        ),
        migrations.AlterField(
            model_name='collabpage',
            name='dealer_support',
            field=models.JSONField(blank=True, default=list, help_text='Додавайте пункти кнопкою нижче — без JSON.', verbose_name='Підтримка дилера'),
        ),
    ]
