# Generated by Django 5.2.17 on 2026-10-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_collab_form_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collabpage',
            name='sub_ru',
        ),
        migrations.RemoveField(
            model_name='collabpage',
            name='sub_uk',
        ),
    ]
