# Generated by Django 5.2.17 on 2026-10-02 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_collab_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactspage',
            name='intro_ru',
        ),
        migrations.RemoveField(
            model_name='contactspage',
            name='intro_uk',
        ),
    ]
