# Generated by Django 5.2.17 on 2026-10-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_contacts_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='body_ru',
            field=models.TextField(blank=True, verbose_name='Текст (ru)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='body_uk',
            field=models.TextField(verbose_name='Текст (ukr)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='evolution_title_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Заголовок еволюції (ru)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='evolution_title_uk',
            field=models.CharField(blank=True, default='Еволюція наших диванів', max_length=128, verbose_name='Заголовок еволюції (ukr)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='milestones_title_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Заголовок віх (ru)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='milestones_title_uk',
            field=models.CharField(blank=True, default='Ключові віхи нашої історії', max_length=128, verbose_name='Заголовок віх (ukr)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='seo_description_ru',
            field=models.TextField(blank=True, verbose_name='SEO description (ru)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='seo_description_uk',
            field=models.TextField(blank=True, verbose_name='SEO description (ukr)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='seo_title_ru',
            field=models.CharField(blank=True, max_length=512, verbose_name='SEO title (ru)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='seo_title_uk',
            field=models.CharField(blank=True, max_length=512, verbose_name='SEO title (ukr)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Підзаголовок (ru)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='subtitle_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Підзаголовок (ukr)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (ru)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title_uk',
            field=models.CharField(max_length=255, verbose_name='Заголовок (ukr)'),
        ),
        migrations.AlterField(
            model_name='collabpage',
            name='advantages_title_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Заголовок переваг (ru)'),
        ),
        migrations.AlterField(
            model_name='collabpage',
            name='advantages_title_uk',
            field=models.CharField(blank=True, default='Наші переваги', max_length=128, verbose_name='Заголовок переваг (ukr)'),
        ),
        migrations.AlterField(
            model_name='collabpage',
            name='dealer_support_title_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Заголовок підтримки дилера (ru)'),
        ),
        migrations.AlterField(
            model_name='collabpage',
            name='dealer_support_title_uk',
            field=models.CharField(blank=True, default='Підтримка нашого дилера:', max_length=128, verbose_name='Заголовок підтримки дилера (ukr)'),
        ),
        migrations.AlterField(
            model_name='collabpage',
            name='form_title_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Заголовок форми (ru)'),
        ),
        migrations.AlterField(
            model_name='collabpage',
            name='form_title_uk',
            field=models.CharField(blank=True, max_length=128, verbose_name='Заголовок форми (ukr)'),
        ),
        migrations.AlterField(
            model_name='collabpage',
            name='seo_description_ru',
            field=models.TextField(blank=True, verbose_name='SEO description (ru)'),
        ),
        migrations.AlterField(
            model_name='collabpage',
            name='seo_description_uk',
            field=models.TextField(blank=True, verbose_name='SEO description (ukr)'),
        ),
        migrations.AlterField(
            model_name='collabpage',
            name='seo_title_ru',
            field=models.CharField(blank=True, max_length=512, verbose_name='SEO title (ru)'),
        ),
        migrations.AlterField(
            model_name='collabpage',
            name='seo_title_uk',
            field=models.CharField(blank=True, max_length=512, verbose_name='SEO title (ukr)'),
        ),
        migrations.AlterField(
            model_name='collabpage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (ru)'),
        ),
        migrations.AlterField(
            model_name='collabpage',
            name='title_uk',
            field=models.CharField(max_length=255, verbose_name='Заголовок (ukr)'),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='form_title_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Заголовок форми (ru)'),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='form_title_uk',
            field=models.CharField(blank=True, default='Напишіть нам', max_length=128, verbose_name='Заголовок форми (ukr)'),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='seo_description_ru',
            field=models.TextField(blank=True, verbose_name='SEO description (ru)'),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='seo_description_uk',
            field=models.TextField(blank=True, verbose_name='SEO description (ukr)'),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='seo_title_ru',
            field=models.CharField(blank=True, max_length=512, verbose_name='SEO title (ru)'),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='seo_title_uk',
            field=models.CharField(blank=True, max_length=512, verbose_name='SEO title (ukr)'),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (ru)'),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='title_uk',
            field=models.CharField(default='Контакти', max_length=255, verbose_name='Заголовок (ukr)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image_alt_ru',
            field=models.CharField(blank=True, max_length=160, verbose_name='Підпис / alt (ru)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image_alt_uk',
            field=models.CharField(blank=True, max_length=160, verbose_name='Підпис / alt (ukr)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_body_ru',
            field=models.TextField(blank=True, verbose_name='Про ROSSA — текст (ru)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_body_uk',
            field=models.TextField(blank=True, verbose_name='Про ROSSA — текст (ukr)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Про ROSSA — заголовок (ru)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_title_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Про ROSSA — заголовок (ukr)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='craft_body_ru',
            field=models.TextField(blank=True, verbose_name='Текст блоку «виробництво» (ru)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='craft_body_uk',
            field=models.TextField(verbose_name='Текст блоку «виробництво» (ukr)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='craft_link_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Текст посилання «Про нас» (ru)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='craft_link_uk',
            field=models.CharField(blank=True, max_length=128, verbose_name='Текст посилання «Про нас» (ukr)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='craft_title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок блоку «виробництво» (ru)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='craft_title_uk',
            field=models.CharField(max_length=255, verbose_name='Заголовок блоку «виробництво» (ukr)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_banner_title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст банера-запрошення (ru)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_banner_title_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст банера-запрошення (ukr)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_bestsellers_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Хіти (ru)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_bestsellers_uk',
            field=models.CharField(default='Популярні моделі', max_length=128, verbose_name='Хіти (ukr)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_categories_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Категорії (ru)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_categories_uk',
            field=models.CharField(default='Категорії', max_length=128, verbose_name='Категорії (ukr)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='seo_description_ru',
            field=models.TextField(blank=True, verbose_name='SEO description (ru)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='seo_description_uk',
            field=models.TextField(blank=True, verbose_name='SEO description (ukr)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='seo_title_ru',
            field=models.CharField(blank=True, max_length=512, verbose_name='SEO title (ru)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='seo_title_uk',
            field=models.CharField(blank=True, max_length=512, verbose_name='SEO title (ukr)'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='body_ru',
            field=models.TextField(blank=True, verbose_name='Текст (ru)'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='body_uk',
            field=models.TextField(verbose_name='Текст (ukr)'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='seo_description_ru',
            field=models.TextField(blank=True, verbose_name='SEO description (ru)'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='seo_description_uk',
            field=models.TextField(blank=True, verbose_name='SEO description (ukr)'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='seo_title_ru',
            field=models.CharField(blank=True, max_length=512, verbose_name='SEO title (ru)'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='seo_title_uk',
            field=models.CharField(blank=True, max_length=512, verbose_name='SEO title (ukr)'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (ru)'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='title_uk',
            field=models.CharField(max_length=255, verbose_name='Заголовок (ukr)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адреса (ru)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address_uk',
            field=models.CharField(max_length=255, verbose_name='Адреса (ukr)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='delivery_label_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Доставка (ru)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='delivery_label_uk',
            field=models.CharField(blank=True, max_length=128, verbose_name='Доставка (ukr)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_tagline_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Підпис у підвалі (ru)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_tagline_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Підпис у підвалі (ukr)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='guarantee_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Гарантія (ru)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='guarantee_uk',
            field=models.CharField(blank=True, max_length=128, verbose_name='Гарантія (ukr)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hours_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Графік (ru)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hours_uk',
            field=models.CharField(max_length=128, verbose_name='Графік (ukr)'),
        ),
        migrations.AlterField(
            model_name='valueprop',
            name='body_ru',
            field=models.TextField(blank=True, verbose_name='Текст (ru)'),
        ),
        migrations.AlterField(
            model_name='valueprop',
            name='body_uk',
            field=models.TextField(verbose_name='Текст (ukr)'),
        ),
        migrations.AlterField(
            model_name='valueprop',
            name='title_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Заголовок (ru)'),
        ),
        migrations.AlterField(
            model_name='valueprop',
            name='title_uk',
            field=models.CharField(max_length=128, verbose_name='Заголовок (ukr)'),
        ),
    ]
