# Generated by Django 5.2.17 on 2026-10-09 07:03

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_homepage_about_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collabpage',
            name='form_image',
            field=core.fields.WebPImageField(blank=True, upload_to='collab/', verbose_name='Фото біля форми'),
        ),
        migrations.AlterField(
            model_name='collabpage',
            name='hero_image',
            field=core.fields.WebPImageField(blank=True, upload_to='collab/', verbose_name='Hero фото'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=core.fields.WebPImageField(upload_to='home/slides/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='craft_image',
            field=core.fields.WebPImageField(blank=True, upload_to='home/', verbose_name='Фото майстерні'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=core.fields.WebPImageField(blank=True, upload_to='brand/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_image',
            field=core.fields.WebPImageField(blank=True, upload_to='brand/', verbose_name='Карта / салон'),
        ),
    ]
